// Dua Lipa's Manifesto Library (Livraria Lello, Porto — a Service95 Book Club
// project). 100 banned / censored / contested titles across four themes: Power,
// Control, Voice, Memory. Static curation mirroring the published list. `slug` is
// set for titles that have a page in our catalog; null = on the list but not (yet)
// a documented ban in our database.
// Source: https://www.service95.com/manifesto-library-launch

export type ManifestoTheme = 'Power' | 'Control' | 'Voice' | 'Memory'

export type ManifestoEntry = {
  title: string
  author: string
  theme: ManifestoTheme
  slug: string | null
}

export const MANIFESTO_THEMES: { key: ManifestoTheme; blurb: string }[] = [
  { key: 'Power', blurb: 'Books that question who holds power and who has the right to speak — confronting political regimes, social systems and cultural norms.' },
  { key: 'Control', blurb: 'Works that expose the machinery of control: surveillance, propaganda, technological influence and ideological conditioning.' },
  { key: 'Voice', blurb: 'Voices pushed to the margins or erased — reclaiming space and narrative authority around race, gender, identity and belonging.' },
  { key: 'Memory', blurb: 'Works that guard memory against forgetting — war, dictatorship, exile and collective trauma.' },
]

export const MANIFESTO_LIBRARY: ManifestoEntry[] = [
  { title: 'A Case of Exploding Mangoes', author: 'Mohammed Hanif', theme: 'Power', slug: 'a-case-of-exploding-mangoes' },
  { title: 'A Dictator Calls', author: 'Ismail Kadare', theme: 'Power', slug: null },
  { title: 'A History of Reading', author: 'Alberto Manguel', theme: 'Power', slug: null },
  { title: 'Felon', author: 'Reginald Dwayne Betts', theme: 'Power', slug: null },
  { title: 'Free', author: 'Lea Ypi', theme: 'Power', slug: null },
  { title: 'Glory', author: 'NoViolet Bulawayo', theme: 'Power', slug: null },
  { title: 'In Cold Blood', author: 'Truman Capote', theme: 'Power', slug: 'in-cold-blood' },
  { title: 'Jerusalem', author: 'Gonçalo M. Tavares', theme: 'Power', slug: null },
  { title: 'Kleptopia', author: 'Tom Burgis', theme: 'Power', slug: null },
  { title: 'Lula Dean\'s Little Library of Banned Books', author: 'Kirsten Miller', theme: 'Power', slug: null },
  { title: 'Men Who Hate Women', author: 'Laura Bates', theme: 'Power', slug: 'men-who-hate-women' },
  { title: 'Nineteen Eighty-Four', author: 'George Orwell', theme: 'Power', slug: '1984' },
  { title: 'One Day, Everyone Will Have Always Been Against This', author: 'Omar El Akkad', theme: 'Power', slug: null },
  { title: 'Putin\'s Russia', author: 'Anna Politkovskaya', theme: 'Power', slug: 'putins-russia' },
  { title: 'The Crucible', author: 'Arthur Miller', theme: 'Power', slug: null },
  { title: 'The Feast of the Goat', author: 'Mario Vargas Llosa', theme: 'Power', slug: null },
  { title: 'The Grapes of Wrath', author: 'John Steinbeck', theme: 'Power', slug: 'the-grapes-of-wrath' },
  { title: 'The Second Sex', author: 'Simone de Beauvoir', theme: 'Power', slug: 'the-second-sex' },
  { title: 'Unfree Speech', author: 'Joshua Wong', theme: 'Power', slug: 'unfree-speech' },
  { title: 'A Clockwork Orange', author: 'Anthony Burgess', theme: 'Control', slug: 'a-clockwork-orange' },
  { title: 'Ai Weiwei on Censorship', author: 'Ai Weiwei', theme: 'Control', slug: null },
  { title: 'Animal Farm', author: 'George Orwell', theme: 'Control', slug: 'animal-farm' },
  { title: 'Blindness', author: 'José Saramago', theme: 'Control', slug: 'blindness' },
  { title: 'Brave New World', author: 'Aldous Huxley', theme: 'Control', slug: 'brave-new-world' },
  { title: 'Careless People', author: 'Sarah Wynn-Williams', theme: 'Control', slug: null },
  { title: 'Fahrenheit 451', author: 'Ray Bradbury', theme: 'Control', slug: 'fahrenheit-451' },
  { title: 'Naked Lunch', author: 'William S. Burroughs', theme: 'Control', slug: 'naked-lunch' },
  { title: 'One Flew Over the Cuckoo\'s Nest', author: 'Ken Kesey', theme: 'Control', slug: 'one-flew-over-the-cuckoos-nest' },
  { title: 'The Accusation', author: 'Bandi', theme: 'Control', slug: 'the-accusation' },
  { title: 'The Burnout Society', author: 'Byung-Chul Han', theme: 'Control', slug: null },
  { title: 'The Handmaid\'s Tale', author: 'Margaret Atwood', theme: 'Control', slug: 'the-handmaids-tale' },
  { title: 'The Hunger Games', author: 'Suzanne Collins', theme: 'Control', slug: 'the-hunger-games' },
  { title: 'The Melancholy of Resistance', author: 'László Krasznahorkai', theme: 'Control', slug: null },
  { title: 'The Memory Police', author: 'Yoko Ogawa', theme: 'Control', slug: null },
  { title: 'The Noise of Time', author: 'Julian Barnes', theme: 'Control', slug: null },
  { title: 'The Trial', author: 'Franz Kafka', theme: 'Control', slug: 'the-trial' },
  { title: 'A Thousand Splendid Suns', author: 'Khaled Hosseini', theme: 'Voice', slug: 'a-thousand-splendid-suns' },
  { title: 'Another Country', author: 'James Baldwin', theme: 'Voice', slug: 'another-country' },
  { title: 'Are You There God? It\'s Me, Margaret', author: 'Judy Blume', theme: 'Voice', slug: 'are-you-there-god-its-me-margaret' },
  { title: 'Born A Crime', author: 'Trevor Noah', theme: 'Voice', slug: 'born-a-crime' },
  { title: 'Decolonising the Mind', author: 'Ngugi wa Thiongo', theme: 'Voice', slug: null },
  { title: 'Erasure', author: 'Percival Everett', theme: 'Voice', slug: null },
  { title: 'Gender Queer', author: 'Maia Kobabe', theme: 'Voice', slug: 'gender-queer' },
  { title: 'Girl, Woman, Other', author: 'Bernardine Evaristo', theme: 'Voice', slug: 'girl-woman-other' },
  { title: 'Hard Like Water', author: 'Yan Lianke', theme: 'Voice', slug: null },
  { title: 'Heartstopper', author: 'Alice Oseman', theme: 'Voice', slug: 'heartstopper' },
  { title: 'I Know Why The Caged Bird Sings', author: 'Maya Angelou', theme: 'Voice', slug: 'i-know-why-the-caged-bird-sings' },
  { title: 'Invisible Man', author: 'Ralph Ellison', theme: 'Voice', slug: 'invisible-man-ellison' },
  { title: 'Milk and Honey', author: 'Rupi Kaur', theme: 'Voice', slug: 'milk-and-honey' },
  { title: 'My Friends', author: 'Hisham Matar', theme: 'Voice', slug: null },
  { title: 'My Pen Is The Wing Of A Bird', author: 'Afghan Women', theme: 'Voice', slug: null },
  { title: 'Nineteen Minutes', author: 'Jodi Picoult', theme: 'Voice', slug: 'nineteen-minutes' },
  { title: 'Olhos d\'Água', author: 'Conceição Evaristo', theme: 'Voice', slug: null },
  { title: 'On Earth We\'re Briefly Gorgeous', author: 'Ocean Vuong', theme: 'Voice', slug: 'on-earth-were-briefly-gorgeous' },
  { title: 'Stamped', author: 'Jason Reynolds', theme: 'Voice', slug: null },
  { title: 'Swimming in the Dark', author: 'Tomasz Jędrowski', theme: 'Voice', slug: null },
  { title: 'That Hair', author: 'Djaimilia Pereira de Almeida', theme: 'Voice', slug: null },
  { title: 'The Absolutely True Diary of a Part-Time Indian', author: 'Sherman Alexie', theme: 'Voice', slug: 'the-absolutely-true-diary-of-a-part-time-indian' },
  { title: 'The Adventures of Huckleberry Finn', author: 'Mark Twain', theme: 'Voice', slug: 'the-adventures-of-huckleberry-finn' },
  { title: 'The Catcher in the Rye', author: 'J. D. Salinger', theme: 'Voice', slug: 'the-catcher-in-the-rye' },
  { title: 'The Color Purple', author: 'Alice Walker', theme: 'Voice', slug: 'the-color-purple' },
  { title: 'The Dark Side of Skin', author: 'Jeferson Tenório', theme: 'Voice', slug: null },
  { title: 'The God of Small Things', author: 'Arundhati Roy', theme: 'Voice', slug: 'the-god-of-small-things' },
  { title: 'The Hate U Give', author: 'Angie Thomas', theme: 'Voice', slug: 'the-hate-u-give' },
  { title: 'The Metamorphosis', author: 'Franz Kafka', theme: 'Voice', slug: 'the-metamorphosis' },
  { title: 'The Satanic Verses', author: 'Salman Rushdie', theme: 'Voice', slug: 'the-satanic-verses' },
  { title: 'The Three Marias', author: 'Maria Isabel Barreno', theme: 'Voice', slug: null },
  { title: 'The Vegetarian', author: 'Han Kang', theme: 'Voice', slug: 'the-vegetarian' },
  { title: 'Their Eyes Were Watching God', author: 'Zora Neale Hurston', theme: 'Voice', slug: 'their-eyes-were-watching-god' },
  { title: 'There There', author: 'Tommy Orange', theme: 'Voice', slug: null },
  { title: 'Things Fall Apart', author: 'Chinua Achebe', theme: 'Voice', slug: 'things-fall-apart' },
  { title: 'This Book Is Gay', author: 'Juno Dawson', theme: 'Voice', slug: 'this-book-is-gay' },
  { title: 'To Kill A Mockingbird', author: 'Harper Lee', theme: 'Voice', slug: 'to-kill-a-mockingbird' },
  { title: 'We Are Displaced', author: 'Malala Yousafzai', theme: 'Voice', slug: null },
  { title: 'We Are Not Numbers', author: 'Ahmed Alnaouq', theme: 'Voice', slug: null },
  { title: 'Beloved', author: 'Toni Morrison', theme: 'Memory', slug: 'beloved' },
  { title: 'Half of a Yellow Sun', author: 'Chimamanda Ngozi Adichie', theme: 'Memory', slug: 'half-of-a-yellow-sun' },
  { title: 'Istanbul: Memories and the City', author: 'Orhan Pamuk', theme: 'Memory', slug: null },
  { title: 'Looking at Women Looking at War', author: 'Victoria Amelina', theme: 'Memory', slug: null },
  { title: 'Maus', author: 'Art Spiegelman', theme: 'Memory', slug: 'maus' },
  { title: 'Oblivion: A Memoir', author: 'Héctor Abad Faciolince', theme: 'Memory', slug: null },
  { title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', theme: 'Memory', slug: 'one-hundred-years-of-solitude' },
  { title: 'Pachinko', author: 'Min Jin Lee', theme: 'Memory', slug: null },
  { title: 'Patriot', author: 'Alexei Navalny', theme: 'Memory', slug: 'patriot-navalny' },
  { title: 'Persepolis', author: 'Marjane Satrapi', theme: 'Memory', slug: 'persepolis' },
  { title: 'Soldiers of Salamis', author: 'Javier Cercas', theme: 'Memory', slug: null },
  { title: 'The Bastard of Istanbul', author: 'Elif Shafak', theme: 'Memory', slug: 'the-bastard-of-istanbul' },
  { title: 'The Book Thief', author: 'Markus Zusak', theme: 'Memory', slug: 'the-book-thief' },
  { title: 'The Books of Jacob', author: 'Olga Tokarczuk', theme: 'Memory', slug: null },
  { title: 'The Diary of a Young Girl', author: 'Anne Frank', theme: 'Memory', slug: 'the-diary-of-a-young-girl' },
  { title: 'The House of the Spirits', author: 'Isabel Allende', theme: 'Memory', slug: 'the-house-of-the-spirits' },
  { title: 'The Kite Runner', author: 'Khaled Hosseini', theme: 'Memory', slug: 'the-kite-runner' },
  { title: 'The Last Kabbalist of Lisbon', author: 'Richard Zimler', theme: 'Memory', slug: null },
  { title: 'The Machine to Make Spaniards', author: 'Valter Hugo Mãe', theme: 'Memory', slug: null },
  { title: 'The Most Secret Memory of Men', author: 'Mohamed Mbougar Sarr', theme: 'Memory', slug: null },
  { title: 'The Murmuring Coast', author: 'Lídia Jorge', theme: 'Memory', slug: null },
  { title: 'The Return', author: 'Dulce Maria Cardoso', theme: 'Memory', slug: null },
  { title: 'The Sympathizer', author: 'Viet Thanh Nguyen', theme: 'Memory', slug: 'the-sympathizer' },
  { title: 'The Unbearable Lightness of Being', author: 'Milan Kundera', theme: 'Memory', slug: 'the-unbearable-lightness-of-being' },
  { title: 'Wild Swans', author: 'Jung Chang', theme: 'Memory', slug: 'wild-swans' },
]

