/**
 * READ-ONLY audit for the "most-popular hit" enrichment contamination:
 * cover images and book descriptions that a title-search fallback copied onto
 * the wrong book (e.g. "The Seven Wonders of the Historic World" wearing the
 * "...Ancient World" cover; Huckleberry Finn's blurb pasted onto dozens of
 * obscure imports).
 *
 * It groups books by shared cover_url and by shared description_book, then
 * flags a group as SUSPECT when the titles inside it are not mutually
 * consistent — i.e. they are different works, not edition/translation variants
 * of one work. The source-side guard now lives in src/lib/enrich/title-match.ts;
 * this script finds the rows that were already poisoned before that guard.
 *
 * Writes nothing to the DB. Outputs:
 *   data/shared-cover-audit.md         — suspect shared-cover groups
 *   data/shared-description-audit.md   — suspect shared-description groups
 *   public/shared-cover-suspects.html  — visual montage of suspect covers
 *
 * Usage:
 *   npx tsx --env-file=.env.local scripts/_audit_shared_enrichment.ts
 */

import { adminClient } from '../src/lib/supabase'
import { titlesMatch, titleTokens } from '../src/lib/enrich/title-match'
import { writeFileSync } from 'node:fs'

type Book = { id: number; title: string; isbn13: string | null; cover_url: string | null; description_book: string | null }

async function fetchAll(): Promise<Book[]> {
  const db = adminClient()
  const rows: Book[] = []
  const PAGE = 1000
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await db
      .from('books')
      .select('id,title,isbn13,cover_url,description_book')
      .order('id', { ascending: true })
      .range(from, from + PAGE - 1)
    if (error) throw error
    if (!data?.length) break
    rows.push(...(data as Book[]))
    if (data.length < PAGE) break
  }
  return rows
}

// Google Books covers vary in their query string; key on the volume id so the
// same image at different zoom levels collapses into one group.
function coverKey(url: string | null): string | null {
  if (!url) return null
  const m = url.match(/[?&]id=([A-Za-z0-9_-]+)/)
  return m ? `gb:${m[1]}` : url
}

/**
 * A group of books is "consistent" (one work, legitimately sharing an asset)
 * when there is an anchor title whose significant tokens are a subset of every
 * other title's — i.e. the others only ADD tokens (subtitle, "(Book 1)",
 * series suffix). Two titles that each carry a distinctive word the other
 * lacks ("Ancient" vs "Historic", "Vol. 3" vs "Vol. 1") break consistency.
 */
function isConsistentGroup(titles: string[]): boolean {
  const uniq = [...new Set(titles)]
  if (uniq.length <= 1) return true
  // Anchor = the title with the fewest significant tokens.
  const anchor = uniq.reduce((a, b) => (titleTokens(a).size <= titleTokens(b).size ? a : b))
  if (titleTokens(anchor).size === 0) return false
  return uniq.every((t) => titlesMatch(anchor, t))
}

function groupBy(books: Book[], keyOf: (b: Book) => string | null): Map<string, Book[]> {
  const m = new Map<string, Book[]>()
  for (const b of books) {
    const k = keyOf(b)
    if (!k) continue
    if (!m.has(k)) m.set(k, [])
    m.get(k)!.push(b)
  }
  return m
}

function main() {
  return fetchAll().then((all) => {
    console.log(`Scanned ${all.length} books`)

    // ── Shared covers ────────────────────────────────────────────────────
    const byCover = groupBy(all, (b) => coverKey(b.cover_url))
    const coverSuspects = [...byCover.entries()]
      .filter(([, v]) => v.length > 1 && !isConsistentGroup(v.map((b) => b.title)))
      .sort((a, b) => b[1].length - a[1].length)

    const coverBooks = coverSuspects.reduce((n, [, v]) => n + v.length, 0)
    let md = `# Shared-cover audit\n\nGenerated by scripts/_audit_shared_enrichment.ts (read-only).\n\n`
    md += `Suspect groups (titles inside don't match → at least one wrong cover): **${coverSuspects.length}** `
    md += `covering **${coverBooks}** books.\n\n`
    for (const [key, v] of coverSuspects) {
      md += `## ${key} — ${v.length} books\n`
      md += `\`${v[0].cover_url}\`\n\n`
      for (const b of v) md += `- #${b.id} ${b.title} (isbn13: ${b.isbn13 ?? '—'})\n`
      md += `\n`
    }
    writeFileSync('data/shared-cover-audit.md', md)

    // Montage so each suspect can be eyeballed (same shape as cover-montage.html).
    let html = `<!doctype html><meta charset="utf-8"><title>Shared-cover suspects</title>`
    html += `<style>body{font:14px system-ui;margin:24px}h2{border-bottom:2px solid #ddd;margin-top:32px}`
    html += `.row{display:flex;gap:14px;flex-wrap:wrap;align-items:flex-start}.card{border:1px solid #e3e3e3;border-radius:8px;padding:8px;width:170px}`
    html += `img{max-width:150px;max-height:200px;background:#f0f0f0;border:1px solid #eee}.t{font-size:12px;margin-top:4px}</style>`
    html += `<h1>Shared-cover suspects (${coverSuspects.length} groups)</h1>`
    for (const [key, v] of coverSuspects) {
      html += `<h2>${key} — ${v.length} books</h2><div class="row">`
      for (const b of v) {
        const src = (b.cover_url ?? '').replace(/&/g, '&amp;')
        html += `<div class="card"><img loading="lazy" src="${src}"><div class="t"><a href="/books/${b.id}" target="_blank">#${b.id}</a> ${b.title}</div></div>`
      }
      html += `</div>`
    }
    writeFileSync('public/shared-cover-suspects.html', html)

    // ── Shared descriptions ──────────────────────────────────────────────
    const byDesc = groupBy(
      all.filter((b) => (b.description_book ?? '').trim().length >= 40),
      (b) => (b.description_book ?? '').trim(),
    )
    const descSuspects = [...byDesc.entries()]
      .filter(([, v]) => v.length > 1 && !isConsistentGroup(v.map((b) => b.title)))
      .sort((a, b) => b[1].length - a[1].length)

    const descBooks = descSuspects.reduce((n, [, v]) => n + v.length, 0)
    let dmd = `# Shared-description audit\n\nGenerated by scripts/_audit_shared_enrichment.ts (read-only).\n\n`
    dmd += `Suspect groups (one blurb on unrelated titles): **${descSuspects.length}** covering **${descBooks}** books.\n\n`
    for (const [desc, v] of descSuspects) {
      dmd += `## ${v.length} books share: "${desc.slice(0, 90).replace(/\n/g, ' ')}…"\n`
      for (const b of v) dmd += `- #${b.id} ${b.title}\n`
      dmd += `\n`
    }
    writeFileSync('data/shared-description-audit.md', dmd)

    console.log(`\nSUSPECT shared covers:       ${coverSuspects.length} groups / ${coverBooks} books`)
    console.log(`SUSPECT shared descriptions: ${descSuspects.length} groups / ${descBooks} books`)
    console.log(`\nWrote:`)
    console.log(`  data/shared-cover-audit.md`)
    console.log(`  data/shared-description-audit.md`)
    console.log(`  public/shared-cover-suspects.html`)
  })
}

main()
