/**
 * READ-ONLY audit for the "poisoned guard" OpenLibrary contamination.
 *
 * Root cause (present since the v2 pipeline shipped, fixed 2026-06-04):
 * olWorks() and olByIsbn() validated their candidate text with
 *   sourceMatches(`${text} ${title} ${author}`, title, author)
 * i.e. they concatenated OUR OWN title + author into the haystack before
 * searching it for that same title + author. The needle was therefore always
 * present and the relevance guard could never reject anything. Combined with
 * OpenLibrary's free-text search returning the most-popular namesake
 * (`olSearch` → limit=1), this pasted e.g. Huckleberry Finn's blurb onto
 * "Bondage Classics".
 *
 * This script re-applies the CORRECTED, un-poisoned guard to every stored
 * openlibrary-sourced description and reports the rows the fixed pipeline would
 * no longer accept, bucketed by how strong the book's OpenLibrary binding is.
 *
 * Writes nothing to the DB. Outputs data/ol-contamination-audit.md and, with
 * --worklist, data/ol-contamination-worklist.json (ids to re-enrich).
 *
 * Usage:
 *   npx tsx --env-file=.env.local scripts/_audit_ol_contamination.ts
 *   npx tsx --env-file=.env.local scripts/_audit_ol_contamination.ts --worklist
 */

import { adminClient } from '../src/lib/supabase'
import { sourceMatches } from '../src/lib/enrich/descriptions-v2'
import { writeFileSync } from 'node:fs'

type Row = {
  id: number
  slug: string
  title: string
  isbn13: string | null
  openlibrary_work_id: string | null
  description_book: string | null
  description_source_url: string | null
  data_quality_status: string | null
  book_authors: Array<{ authors: { display_name: string } | null }>
}

const WORKLIST = process.argv.includes('--worklist')

async function fetchAll(): Promise<Row[]> {
  const db = adminClient()
  const rows: Row[] = []
  const PAGE = 1000
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await db
      .from('books')
      .select('id,slug,title,isbn13,openlibrary_work_id,description_book,description_source_url,data_quality_status,book_authors(authors(display_name))')
      .eq('description_source_type', 'openlibrary')
      .order('id', { ascending: true })
      .range(from, from + PAGE - 1)
    if (error) throw error
    if (!data?.length) break
    rows.push(...(data as unknown as Row[]))
    if (data.length < PAGE) break
  }
  return rows
}

type Binding = 'isbn' | 'work_id' | 'search'
function bindingOf(r: Row): Binding {
  if (r.isbn13) return 'isbn'
  if (r.openlibrary_work_id) return 'work_id'
  return 'search'
}

/**
 * Would the corrected pipeline still accept this stored openlibrary text?
 *  - isbn binding  → strict (olByIsbn): text must match.
 *  - work_id binding → lenient (olWorks true): short (≤300) accepted on binding.
 *  - search binding → strict (olWorks false): text must match.
 */
function stillAccepted(r: Row, author: string): boolean {
  const text = r.description_book ?? ''
  const matched = sourceMatches(text, r.title, author)
  if (matched) return true
  if (bindingOf(r) === 'work_id' && text.length <= 300) return true
  return false
}

async function main() {
  const all = await fetchAll()
  console.log(`Scanned ${all.length} openlibrary-sourced descriptions`)

  const contaminated: Array<Row & { author: string; binding: Binding; len: number }> = []
  const byBinding: Record<Binding, { total: number; bad: number }> = {
    isbn: { total: 0, bad: 0 }, work_id: { total: 0, bad: 0 }, search: { total: 0, bad: 0 },
  }

  for (const r of all) {
    const author = r.book_authors?.[0]?.authors?.display_name ?? ''
    const b = bindingOf(r)
    byBinding[b].total++
    if (!stillAccepted(r, author)) {
      byBinding[b].bad++
      contaminated.push({ ...r, author, binding: b, len: (r.description_book ?? '').length })
    }
  }

  contaminated.sort((a, b) => (a.binding < b.binding ? -1 : a.binding > b.binding ? 1 : b.len - a.len))

  let md = `# OpenLibrary "poisoned guard" contamination audit\n\n`
  md += `Generated by scripts/_audit_ol_contamination.ts (read-only). Re-applies the\n`
  md += `corrected un-poisoned guard to every stored openlibrary description.\n\n`
  md += `Total openlibrary descriptions scanned: **${all.length}**\n\n`
  md += `| binding | total | rejected by fixed guard |\n|---|---:|---:|\n`
  for (const b of ['isbn', 'work_id', 'search'] as Binding[]) {
    md += `| ${b} | ${byBinding[b].total} | ${byBinding[b].bad} |\n`
  }
  md += `\n**Total contaminated: ${contaminated.length}**\n\n`
  md += `These descriptions do not mention their book's own title or author and\n`
  md += `would be rejected by the fixed pipeline. Recommended remediation: clear\n`
  md += `description_book + provenance and set data_quality_status='flagged' so the\n`
  md += `fixed pipeline re-enriches them from a verified source.\n\n`

  for (const b of ['search', 'isbn', 'work_id'] as Binding[]) {
    const rows = contaminated.filter(c => c.binding === b)
    if (!rows.length) continue
    md += `## binding=${b} — ${rows.length} contaminated\n\n`
    for (const c of rows) {
      const snippet = (c.description_book ?? '').replace(/\s+/g, ' ').slice(0, 110)
      md += `- #${c.id} **${c.title}** — ${c.author || '(no author)'} (${c.len}c)\n`
      md += `  - ${c.description_source_url ?? '—'}\n`
      md += `  - "${snippet}…"\n`
    }
    md += `\n`
  }

  writeFileSync('data/ol-contamination-audit.md', md)
  console.log(`\nContaminated by binding:`)
  for (const b of ['isbn', 'work_id', 'search'] as Binding[]) {
    console.log(`  ${b}: ${byBinding[b].bad}/${byBinding[b].total}`)
  }
  console.log(`\nTOTAL contaminated: ${contaminated.length}`)
  console.log(`Wrote data/ol-contamination-audit.md`)

  if (WORKLIST) {
    writeFileSync('data/ol-contamination-worklist.json', JSON.stringify(contaminated.map(c => c.id), null, 2))
    console.log(`Wrote data/ol-contamination-worklist.json (${contaminated.length} ids)`)
  }
}

main().catch(e => { console.error(e); process.exit(1) })
