import { adminClient } from '../src/lib/supabase'

const supabase = adminClient()

const descriptions: Record<string, string> = {
  CN: `China operates one of the world's most extensive censorship apparatuses, overseen by the General Administration of Press and Publication and reinforced by party directives and the Great Firewall. Works that challenge Communist Party authority, document suppressed historical events — the Great Leap Forward famine, the Cultural Revolution, the Tiananmen Square massacre — or support Tibetan or Uyghur cultural identity are systematically banned. Chinese-language editions of banned books circulate in Hong Kong and Taiwan; foreign editions are confiscated at customs. Nobel Peace Prize laureate Liu Xiaobo's writings remain banned in mainland China, where even his name is censored online.`,

  VA: `The Catholic Church's Index Librorum Prohibitorum — the Index of Prohibited Books — was in force from 1559 until 1966, listing titles forbidden to faithful Catholics on pain of excommunication. At its peak, the Index included works by Galileo, Copernicus, Descartes, Locke, Voltaire, and Hume — essentially the intellectual foundations of the modern world. Books were condemned for heresy, moral unsuitability, or challenges to Church authority. The Index was formally abolished in 1966 by Pope Paul VI, though the Church retained the right to caution the faithful about dangerous works. The history of the Index is a central chapter in the history of censorship.`,

  ES: `Spain's most sustained period of literary censorship came under Francisco Franco's dictatorship (1939–1975). The regime established a formal censorship apparatus that banned thousands of titles, particularly targeting works in regional languages — Catalan, Basque, Galician — as Franco sought to impose Castilian monoculture. Spanish authors who wrote from exile faced having their work banned at home. Federico García Lorca, Spain's greatest 20th-century poet, had been murdered by Nationalist forces in 1936. The transition to democracy after Franco's death led to rapid liberalisation, and Spain today has strong press freedom protections.`,

  IN: `India's constitutional right to free speech is qualified by provisions allowing restrictions on grounds of sovereignty, security, public order, morality, and community harmony — clauses that have been invoked repeatedly to ban books. State governments and courts have ordered bans on works deemed offensive to religious communities, with Hindu nationalist groups frequently petitioning for restrictions on academic histories and literary works. India was the first country to ban Salman Rushdie's The Satanic Verses in 1988, before the book was even published in the UK. Several books dealing with caste, religious minorities, or historical revisionism have been banned or withdrawn under legal pressure.`,

  RU: `The Russian Empire censored literature extensively through the tsarist censor, who reviewed all publications. The Soviet period (see Soviet Union) brought industrialised censorship through Glavlit and Writers' Union controls. Post-Soviet Russia initially expanded press freedom, but Putin's consolidation of power has dramatically contracted it. Laws against "discrediting the armed forces," LGBTQ+ "propaganda," and foreign agent designations have been used to suppress books. The 2022 full-scale invasion of Ukraine triggered a fresh wave of restrictions on writers and journalists critical of the war.`,

  SA: `Saudi Arabia bans books under criteria that include anything contrary to Islamic values, critical of the royal family or government, sexually explicit, or promoting non-Muslim religions. The kingdom's annual Riyadh International Book Fair routinely sees hundreds of titles prohibited from display. Works addressing women's rights, LGBTQ+ topics, religious doubt, or political dissent are systematically excluded. The murder of journalist Jamal Khashoggi in 2018 drew renewed global attention to Saudi Arabia's suppression of free expression, which extends far beyond book banning to imprisonment of poets and writers.`,

  CS: `Czechoslovakia under Communist rule (1948–1989) maintained comprehensive censorship through the Central Publications Board. The Prague Spring of 1968 briefly opened cultural expression before the Warsaw Pact invasion restored repression through "normalisation," which lasted until 1989. Dissident writers whose books were banned domestically circulated their work through samizdat networks; Milan Kundera, Václav Havel, and Bohumil Hrabal all had works banned for extended periods. The Velvet Revolution of 1989 ended censorship, and Václav Havel — once a banned playwright — became the country's first post-communist president.`,

  IT: `Italy's most intense period of literary censorship came under Mussolini's Fascist dictatorship (1925–1943), when the regime banned foreign works, anti-fascist texts, and books by Jewish authors. Public book burnings were organised in imitation of Nazi Germany. The Catholic Church's Index of Prohibited Books (enforced until 1966) also shaped what Italian publishers would risk printing. Post-war Italy has strong constitutional protections for free expression, and book censorship is rare today, though some prosecutions for obscenity and defamation have occurred.`,

  TR: `Turkey has banned hundreds of books under laws targeting incitement to hatred, insulting Turkishness (Article 301 of the Penal Code), and separatist propaganda. Writers whose works touch on the Armenian Genocide, Kurdish identity, or criticism of the state have faced prosecution. Nobel laureate Orhan Pamuk was tried under Article 301 in 2005 before charges were dropped. Author Elif Şafak faced similar prosecution in 2006. Yaşar Kemal — celebrated internationally for his novels about Kurdish peasant life — was repeatedly prosecuted. Turkey consistently ranks poorly on global press freedom indices.`,

  CU: `Cuba under Fidel Castro's revolution (1959 onwards) established state control over all publishing. Works deemed insufficiently revolutionary or critical of the government were banned. The Padilla Affair of 1971 — in which poet Heberto Padilla was imprisoned, forced into a public confession, and then freed under international pressure — was a turning point in the relationship between the Cuban revolution and the international literary left. Books by exiled Cuban writers remain largely unavailable in Cuba. The state controls what may be published, distributed, and imported.`,

  ZA: `Under apartheid (1948–1994), South Africa's censorship apparatus — formalised in the Publications and Entertainments Act of 1963 — banned thousands of books. Works by Black South African writers, anti-apartheid literature, and anything sympathetic to the liberation movement were systematically suppressed. André Brink, Athol Fugard, and Breyten Breytenbach are among the many writers who had books banned. The post-apartheid Constitution, adopted in 1996, includes one of the world's most expansive free expression provisions, and formal book censorship has effectively ended.`,

  PL: `Poland under Communist rule (1944–1989) maintained state censorship through the Główny Urząd Kontroli Prasy, Publikacji i Widowisk (Central Office for the Control of the Press, Publications, and Public Performances). The underground Solidarność movement developed an extensive samizdat publishing network. The end of communism in 1989 brought full press freedom. Poland's post-communist governments have generally respected free expression, though the period of PiS rule (2015–2023) raised concerns about cultural pressures on public institutions.`,

  KR: `South Korea banned books under anti-communist legislation during the Cold War, particularly the National Security Law, which criminalised works deemed sympathetic to North Korea. The authoritarian governments of Park Chung-hee and Chun Doo-hwan (1961–1987) practised extensive censorship of political dissent. The democratic transition of 1987 dramatically expanded literary freedom, though some sensitive topics — including positive portrayals of North Korea — remain legally restricted under a law that critics argue is frequently abused.`,

  EG: `Egypt's Al-Azhar University — one of Sunni Islam's most prestigious institutions — has historically played a role in Egyptian censorship by issuing fatwas against books deemed blasphemous or offensive to Islam. The Egyptian government has also restricted works on political grounds, particularly since the military-backed government came to power in 2013. Nobel laureate Naguib Mahfouz was stabbed in 1994 by an Islamist motivated by a fatwa against one of his novels, and his book Sons of Gebelawi remains banned in Egypt. The country periodically restricts works addressing LGBTQ+ topics, religious dissent, or political opposition.`,

  GR: `Greece banned books under the military junta (1967–1974), during which literature by left-wing writers and poetry with political themes were suppressed. The junta burned books and imprisoned writers and artists, including composer Mikis Theodorakis. The Orthodox Church has on occasion sought to restrict blasphemous content, and post-junta governments have prosecuted a small number of writers for religiously offensive works. Greece today has strong press freedom protections and ranks well on international indices.`,

  ID: `Under Suharto's New Order government (1966–1998), Indonesia maintained an extensive censorship apparatus that banned thousands of books — particularly those by communist or leftist authors, works relating to the 1965 anti-communist massacres, and Pramoedya Ananta Toer's celebrated Buru Quartet (written while Pramoedya was imprisoned on Buru Island). Post-Suharto Indonesia has substantially liberalised, but some sensitive topics — atheism, communism, and works deemed blasphemous — remain subject to restriction by government and religious authorities.`,

  PT: `Portugal under António de Oliveira Salazar's Estado Novo dictatorship (1933–1974) maintained a comprehensive censorship regime. The PIDE secret police reviewed and suppressed books critical of the regime, colonial policy, or the Catholic Church. Authors including Aquilino Ribeiro and José Saramago published works that were censored or faced legal action. The Carnation Revolution of 1974 ended dictatorship and censorship; Portugal today consistently ranks in the top tier of global press freedom indices.`,

  PH: `Under Spanish colonial rule, Philippine authorities banned Noli Me Tángere and other works by José Rizal as subversive to colonial order and the Catholic Church — a ban that helped trigger the revolution that eventually ended Spanish rule. After independence, successive governments periodically restricted publications deemed threats to national security, particularly during the Marcos dictatorship (1972–1986), when martial law enabled broad censorship powers. The Philippines today has a constitutionally protected free press, though journalists and authors continue to face pressure.`,

  JP: `Japan's prewar and wartime governments (1930s–1945) imposed strict censorship on publications deemed subversive, pacifist, or contrary to militarist ideology. Postwar Japan established strong free expression protections, but the country maintains obscenity laws that have been used — most famously in the prosecution of Lady Chatterley's Lover in 1957 — to restrict sexual content. Japan's approach to manga and graphic content remains a subject of periodic controversy.`,

  KP: `North Korea operates the world's most comprehensive state censorship regime. All publications are produced and controlled by the Korean Workers' Party, and unauthorised possession of foreign media is a criminal offence. Books critical of the Kim family dynasty, South Korean publications, and virtually all foreign literature are banned. The country's official literary production is entirely devoted to state propaganda. North Korean defectors describe elaborate systems for smuggling banned books and USB drives across the Chinese border.`,

  AR: `Argentina's military dictatorships — and most completely the Process of National Reorganisation (1976–1983) — maintained extensive lists of banned books. Left-wing literature, works by authors in exile, books dealing with politics or sexuality, and anything deemed subversive was prohibited. Publishers, authors, and booksellers were among the approximately 30,000 people who were "disappeared" during the dictatorship. The return of democracy in 1983 ended formal censorship, and Argentina today has strong constitutional free expression protections.`,

  BR: `Brazil has experienced several periods of literary censorship, most notably under the Estado Novo dictatorship of Getúlio Vargas (1937–1945), which included public book burnings in 1937, and during the military dictatorship (1964–1985). Under the military regime, the AI-5 decree of 1968 gave censors sweeping powers; books, films, and music were all targeted. Brazil today is a democracy with constitutional press freedom protections, though violence against journalists remains a serious concern.`,

  CL: `Chile under Augusto Pinochet's dictatorship (1973–1990) banned thousands of books and burned collections in public squares in the weeks after the September 1973 coup. Left-wing literature, works by exiled authors, and political writings were systematically suppressed. Pablo Neruda — Chile's most celebrated poet and a committed communist — died eleven days after the coup; his home was ransacked. The return of democracy restored press freedom, and Chile today ranks well on international press freedom indices.`,

  UA: `Ukraine's literary suppression has been driven primarily by external powers. The Russian Empire's Ems Decree of 1876 banned Ukrainian-language publications and education. Soviet rule brought the Executed Renaissance — the mass arrest and killing of Ukrainian intellectuals in the 1930s — and continued restrictions on Ukrainian cultural expression. Since Russia's 2022 full-scale invasion, Ukrainian books and authors have been targeted for confiscation in occupied territories, and Russia has banned Ukrainian-language literature across occupied regions as part of systematic cultural erasure.`,

  BY: `Belarus under Alexander Lukashenko (since 1994, and particularly after the fraudulent 2020 election) has suppressed independent publishing and journalism. Books by opposition figures, literature addressing political dissent, and works by Belarusian Nobel laureate Svetlana Alexievich have been restricted or removed from libraries. Alexievich, internationally celebrated for works like Voices from Chernobyl, was forced into exile in 2020 after the crackdown on the protest movement.`,

  SY: `Syria under Hafez al-Assad and his son Bashar has maintained comprehensive censorship of books and media. The country's state of emergency (in force 1963–2011) gave authorities broad powers to suppress publications. Works critical of the Assad government, challenging official narratives about the Ba'ath Party's history, or touching on sensitive sectarian topics have been banned. Authors have faced imprisonment and exile. The civil war that began in 2011 further disrupted the publishing and literary environment.`,

  IQ: `Iraq under Saddam Hussein's Ba'athist government (1968–2003) maintained strict censorship of books and media, with works critical of the regime or Saddam personally facing severe consequences. The regime also suppressed Kurdish literature and cultural expression as part of the Arabisation campaign. Post-2003 Iraq has had a more open publishing environment, though security conditions and political instability have hampered the literary sector.`,

  IR: `Iran has maintained strict state censorship since the Islamic Revolution of 1979, with the Ministry of Culture and Islamic Guidance required to approve all publications. Works contrary to Islamic values, critical of the government, or sexually explicit are routinely banned. The 1989 fatwa issued by Ayatollah Khomeini against Salman Rushdie for The Satanic Verses forced Rushdie into hiding for nearly a decade and remains the most internationally prominent act of literary censorship in modern history.`,

  NO: `Norway has historically restricted publications on grounds of obscenity, with Lady Chatterley's Lover, Lolita, and Henry Miller's Tropic of Cancer all banned for periods in the 20th century. Post-war Norwegian censorship was moderate by European standards, and the country today consistently ranks near the top of global press freedom indices. Modern Norway has no formal book censorship regime.`,

  DK: `Denmark maintained obscenity restrictions through much of the 20th century, with works such as Story of O and Lolita banned for periods. Denmark was among the first Western countries to fully liberalise its obscenity laws, abolishing restrictions on written material in 1967 — a watershed that influenced other countries. Denmark today has some of the strongest press freedom protections in the world.`,

  PY: `Paraguay under General Alfredo Stroessner's dictatorship (1954–1989) — one of the longest-lasting in Latin American history — maintained comprehensive censorship of books, press, and media. Works by the country's greatest writer, Augusto Roa Bastos, were banned; Roa Bastos spent most of his adult life in exile. Opposition literature, works on social justice, and books by exiled Paraguayan writers were suppressed. The end of the dictatorship in 1989 restored press freedom.`,

  LY: `Libya under Muammar Gaddafi's 42-year dictatorship (1969–2011) banned books critical of the regime, works by opposition writers, and literature challenging Gaddafi's own ideological treatise, The Green Book. Libyan author Hisham Matar's family was persecuted by the regime; Matar's father, a prominent dissident, was abducted by Gaddafi agents and disappeared into Libyan prisons. Post-Gaddafi Libya has faced profound instability that has made a regular publishing environment difficult to establish.`,
}

async function main() {
  let updated = 0
  for (const [code, description] of Object.entries(descriptions)) {
    const { error } = await supabase
      .from('countries')
      .update({ description })
      .eq('code', code)
      .is('description', null)

    if (error) {
      console.error(`Error updating ${code}:`, error.message)
    } else {
      console.log(`  Updated: ${code}`)
      updated++
    }
  }
  console.log(`\nUpdated ${updated} country descriptions.`)
}

main().catch(console.error)
