-- Short attention-grabbing headline above the bron-titel on the news surfaces
-- (homepage block, /news page, RSS). Generated by the same OpenAI call as the
-- summary going forward; existing rows are backfilled via
-- scripts/backfill-news-headlines.ts. Nullable so the column can roll out
-- before the backfill completes — UI falls back to the bron-titel when null.

alter table public.news_items
  add column if not exists headline text;
